# Generated by .github/workflows/update-formula.yml from the camy release
# channel; the checksums are the ones in the cosign-verified
# SHA256SUMS-1.0.1. Do not edit by hand.
class Camy < Formula
  desc "Camy in your terminal: the same agent, memory, and cloud computer you use at camy.ai"
  homepage "https://camy.ai"
  version "1.0.1"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://dl.camy.sh/stable/camy_1.0.1_darwin_arm64.tar.gz"
      sha256 "6f67a3d86752ef7f2f457f0b01aa6b2098861011d2a6dad2593d4ae19aece0a0"
    end
    on_intel do
      url "https://dl.camy.sh/stable/camy_1.0.1_darwin_amd64.tar.gz"
      sha256 "86ff245a169ceaf481af628810cfbd668091fc0854bfa38ed0688601cb04eea5"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.camy.sh/stable/camy_1.0.1_linux_arm64.tar.gz"
      sha256 "a113c0ce41032e3eaf49379438308332a3015fcf1500373286acf057c708074a"
    end
    on_intel do
      url "https://dl.camy.sh/stable/camy_1.0.1_linux_amd64.tar.gz"
      sha256 "8b35ff276c573e83f21d749b96109d41b1f823373c5e318c59c686e886905723"
    end
  end

  def install
    bin.install "camy"
    bash_completion.install "completions/camy.bash" => "camy" if File.exist?("completions/camy.bash")
    zsh_completion.install "completions/camy.zsh" => "_camy" if File.exist?("completions/camy.zsh")
    fish_completion.install "completions/camy.fish" if File.exist?("completions/camy.fish")
    man1.install Dir["manpages/*.1.gz"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/camy version")
  end
end
