# Generated by .github/workflows/update-formula.yml from the camy release
# channel; the checksums are the ones in the cosign-verified
# SHA256SUMS-1.0.0. Do not edit by hand.
class Camy < Formula
  desc "Camy in your terminal: the same agent, memory, and cloud computer you use at camy.ai"
  homepage "https://camy.ai"
  version "1.0.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://dl.camy.sh/stable/camy_1.0.0_darwin_arm64.tar.gz"
      sha256 "ac51a108cee7759cdaeb7c858acdb98ef7a9a236063c93eab0fe14795cecc5bd"
    end
    on_intel do
      url "https://dl.camy.sh/stable/camy_1.0.0_darwin_amd64.tar.gz"
      sha256 "aaf933b9e50820e7ebdc1764eef850bb49ee8126efb7bbb295e57f0746d7a657"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.camy.sh/stable/camy_1.0.0_linux_arm64.tar.gz"
      sha256 "f071aacfb4ad016da38b9466ea247ad78125ccb062b59bb11c7bd0be507878d6"
    end
    on_intel do
      url "https://dl.camy.sh/stable/camy_1.0.0_linux_amd64.tar.gz"
      sha256 "f088f99465a1231915f7846c28873e17ad5ab358649ae2dcf0bb723ce5f61bc7"
    end
  end

  def install
    bin.install "camy"
    bash_completion.install "completions/camy.bash" => "camy" if File.exist?("completions/camy.bash")
    zsh_completion.install "completions/camy.zsh" => "_camy" if File.exist?("completions/camy.zsh")
    fish_completion.install "completions/camy.fish" if File.exist?("completions/camy.fish")
    man1.install Dir["manpages/*.1.gz"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/camy version")
  end
end
